iseek_backend/blog/urls.py
# -*- coding:utf-8 -*-

from django.urls import path, include
from rest_framework import routers
from . import views

api_router = routers.DefaultRouter()
api_router.register(r'topics', views.TopicAPIView, base_name='api_topics')
api_router.register(r'tags', views.TagAPIView, base_name='api_tags')
api_router.register(r'articles', views.ArticleAPIView, base_name='api_articles')
api_router.register(r'archives', views.ArchiveAPIView, base_name='api_archives')

urlpatterns = [
    path(r'', views.IndexView.as_view(), name='index'),

    path('article/<int:id>', views.article_detail, name='detail'),
    path('topic/<int:id>', views.topic, name='topic'),
    path('tag/<int:id>', views.tag, name='tag'),

    path('article', views.article_list, name='article_list'),
    path('about', views.about, name='about'),

    path('api/', include(api_router.urls)),
]

iseek_backend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('blog.urls', 'blog'), namespace='blog'), name='blog'),
]

iseek_backend/blog/models.py
# -*- coding:utf-8 -*-
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
from mptt.models import MPTTModel, TreeForeignKey


class Tag(models.Model):
    """
    文章的标签
    """
    name = models.CharField('文章标签', max_length=20)
    slug = models.SlugField(unique=True)
    desc = models.TextField('描述', max_length=255, default='')

    class Meta:
        verbose_name = '标签'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """ 查看该标签下的所有文章列表 """
        return reverse('blog:tag', kwargs={'id': self.id})


class Topic(MPTTModel):
    """
    文章分类、主题
    """
    name = models.CharField('文章分类', max_length=20)
    slug = models.SlugField(unique=True)
    desc = models.TextField('此分类的描述', max_length=256, default='')

    # 用于构建多级分类树
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children',
                            on_delete=models.CASCADE, db_index=True)

    class Meta:
        verbose_name = '分类'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """ 查看该分类下的所有文章列表 """
        return reverse('blog:topic', kwargs={'id': self.id})


class Article(models.Model):
    """
    文章内容
    """
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='作者')
    title = models.CharField(max_length=150, verbose_name='文章标题')
    summary = models.TextField('文章摘要', max_length=256,
                               default='文章摘要将显示在首页，必须填写...')
    text = models.TextField(verbose_name='文章内容')
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    update_time = models.DateTimeField(verbose_name='更新时间', auto_now=True)
    slug = models.SlugField(unique=True)

    # 文章和主题是多对一的关系
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, verbose_name='文章分类')

    # 文章和标签是多对多的关系
    tags = models.ManyToManyField(Tag, verbose_name='文章标签')

    class Meta:
        verbose_name = '文章'
        ordering = ['-create_time']

    def __str__(self):
        # 显示前20个字符和省略号
        s = self.title[:20]
        return s if len(self.title) < 20 else s + ' ...'

    def get_absolute_url(self):
        """ 查看该文章的具体内容 """
        return reverse('blog:detail', kwargs={'id': self.id})

    def get_pre(self):
        return Article.objects.filter(id__lt=self.id).order_by('-id').first()

    def get_next(self):
        return Article.objects.filter(id__gt=self.id).order_by('id').first()

iseek_backend/blog/views.py
# -*- coding:utf-8 -*-

import os
from collections import OrderedDict

from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.conf import settings
from django.core.cache import cache
from django.db.models.aggregates import (Count, Q)
from rest_framework import viewsets
from rest_framework.pagination import PageNumberPagination
from rest_framework.response import Response
from rest_framework.decorators import action

from iseek_backend.settings import BASE_DIR
from .serializers import (
    TopicSerializer, TagSerializer, ArticleSerializer, SimpleArticleSerializer,
    SmallArticleSerializer
)

import markdown

from .models import (Tag, Topic, Article)


class IndexView(generic.ListView):
    model = Article
    template_name = 'index.html'
    context_object_name = 'articles'
    paginate_by = 5
    # paginate_orphans = 3

    def get_ordering(self):
        ordering = super(self.__class__, self).get_ordering()
        sort = self.kwargs.get('sort')
        if sort == 'v':
            return ('-views', '-update_date', '-id')
        return ordering


def article_detail(request, id):
    article = get_object_or_404(Article, pk=id)

    update_time = article.update_time.strftime("%Y%m%d%H%M%S")
    md_key = '{}_md_{}'.format(article.id, update_time)
    cache_md = cache.get(md_key)
    if cache_md:
        md = cache_md
    else:
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
            # TocExtension(slugify=slugify),
        ])
        cache.set(md_key, md, 60 * 60 * 12)
    article.text = md.convert(article.text)
    article.toc = md.toc    # 目录

    context = {
        'article': article
    }
    return render(request, 'detail.html', context=context)


def article_list(request):
    tag_id = request.GET.get('tag_id', None)
    topic_id = request.GET.get('topic_id', None)
    articles = None
    if tag_id:
        articles = Article.objects.filter(tags=int(tag_id))
    if topic_id:
        articles = Article.objects.filter(topic_id=int(topic_id))

    context = {
        'articles': articles,
    }
    return render(request, 'article_list.html', context=context)


def about(request):
    about_file = os.path.join(BASE_DIR, 'doc', 'about.md')
    file = open(about_file, 'r')

    md_key = '{}_md'.format('about')
    cache_md = cache.get(md_key)
    if cache_md:
        md = cache_md
    else:
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
            # TocExtension(slugify=slugify),
        ])
        cache.set(md_key, md, 60 * 60 * 12)
    about_text = md.convert(file.read())
    return render(request, 'about.html', context={'about_text': about_text})


def topic(request, id):
    topic = get_object_or_404(Topic, pk=id)
    articles = Article.objects.filter(topic=topic)
    context = {
        'topic': topic,
        'articles': articles,
    }
    return render(request, 'topic.html', context=context)


def tag(request, id):
    tag = get_object_or_404(Tag, pk=id)
    articles = Article.objects.filter(tags=tag)
    context = {
        'tag': tag,
        'articles': articles,
    }
    return render(request, 'tag.html', context=context)


class CustomPagination(PageNumberPagination):
    page_size = 8

    def get_paginated_response(self, data):
        _next = self.page.next_page_number() if self.page.has_next() else None
        _pre = self.page.previous_page_number() if self.page.has_previous() else None
        _count = self.page.paginator.count
        _size = self.page_size

        _pages = _count // _size if _count % _size == 0 else _count // _size + 1

        page = OrderedDict([
            ('count', _count),
            # ('last', self.page.paginator.count),
            # ('offset', _size),
            ('pages', _pages),
            ('pre', _pre),
            ('current', self.page.number),
            ('next', _next),
            # ('nextLink', self.get_next_link()),
            # ('preLink', self.get_previous_link())
        ])

        return Response(OrderedDict([
            ('page', page),
            ('results', data)
        ]))


class TopicAPIView(viewsets.ReadOnlyModelViewSet):
    queryset = Topic.objects.all().order_by('id')
    serializer_class = TopicSerializer
    pagination_class = CustomPagination

    def get_queryset(self):
        return Topic.objects.annotate(total=Count('article')).filter(total__gt=0)


class TagAPIView(viewsets.ReadOnlyModelViewSet):
    queryset = Tag.objects.exclude(article__isnull=True).annotate(total=Count('article')).order_by('id')
    serializer_class = TagSerializer
    pagination_class = CustomPagination

    def get_queryset(self):
        article_id = self.request.query_params.get('article', None)

        qs = self.queryset
        if article_id:
            article_id = int(article_id)
            qs = self.queryset.filter(article=article_id)

        return qs


class ArticleAPIView(viewsets.ReadOnlyModelViewSet):
    queryset = Article.objects.all().order_by('create_time')
    serializer_class = ArticleSerializer
    pagination_class = CustomPagination
    # paginate_by = getattr(settings, 'PAGE_LIMIT', 10)

    def get_queryset(self):
        topic_id = self.request.query_params.get('topic', None)
        tag_id = self.request.query_params.get('tag', None)
        search = self.request.query_params.get('search', None)

        qs = self.queryset
        if topic_id:
            topic_id = int(topic_id)
            qs = self.queryset.filter(topic=topic_id)

        if tag_id:
            tag_id = int(tag_id)
            qs = self.queryset.filter(tags=tag_id)

        if search:
            qs = Article.objects.filter(title__icontains=search)

        return qs

    def list(self, request, *args, **kwargs):
        queryset = self.filter_queryset(self.get_queryset())

        page = self.paginate_queryset(queryset)
        if page is not None:
            serializer = SimpleArticleSerializer(page, many=True)
            return self.get_paginated_response(serializer.data)

        serializer = SimpleArticleSerializer(queryset, many=True)
        return Response(serializer.data)

    def retrieve(self, request, *args, **kwargs):
        instance = self.get_object()
        serializer = self.get_serializer(instance)
        article = serializer.data
        if not article:
            return Response({})

        utime = article['utime'].split(' ')[0]      # date str
        md_key = '{}_md_{}'.format(article['id'], utime)
        cache_md = cache.get(md_key)
        if cache_md:
            md = cache_md
        else:
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
                'markdown.extensions.toc',
                # TocExtension(slugify=slugify),
            ])
            cache.set(md_key, md, 60 * 60 * 12)
        article['text'] = md.convert(article['text'])
        article['toc'] = md.toc  # 目录

        _next = instance.get_next()
        _pre = instance.get_pre()
        article['next'] = {
            'id': _next.id,
            'title': _next.title
        } if _next else None
        article['pre'] = {
            'id': _pre.id,
            'title': _pre.title
        } if _pre else None
        return Response(article)

    @action(detail=False, methods=['get'], url_path='search')
    def search(self, request, *args, **kwargs):
        q = self.request.query_params.get('q', None)
        if not q:
            return Response({})

        qs = Article.objects.filter(Q(title__icontains=q) | Q(slug__icontains=q))
        page = self.paginate_queryset(qs)
        if page is not None:
            serializer = SimpleArticleSerializer(page, many=True)
            return self.get_paginated_response(serializer.data)

        serializer = SimpleArticleSerializer(qs, many=True)
        return Response(serializer.data)


class ArchiveAPIView(viewsets.ReadOnlyModelViewSet):
    queryset = Article.objects.all().order_by('-create_time')
    serializer_class = SmallArticleSerializer

    def get_queryset(self):
        topic_id = self.request.query_params.get('topic', None)

        qs = self.queryset
        if topic_id:
            topic_id = int(topic_id)
            qs = self.queryset.filter(topic=topic_id)

        return qs

    def list(self, request, *args, **kwargs):
        queryset = self.filter_queryset(self.get_queryset())
        sort = dict()
        for article in queryset:
            year = str(article.create_time.year)
            if year not in sort:
                sort[year] = list()

            sort[year].append(article)

        results = dict()
        for year, articleList in sort.items():
            if year not in results:
                results[year] = {
                    'total': len(articleList),
                    'data': SmallArticleSerializer(articleList, many=True).data
                }

        return Response(results)

        """
        {
            '2018': {
                total: 10,
                data: [
                    {1, 'a', '2018-10-20'}, 
                    {2, 'b', '2018-10-21'}
                ]
        }
        """

iseek_backend/blog/templates/about.html
{% extends 'base.html' %}

{% block blog_title %}关于博客{% endblock %}

{% block base_content %}

<div class="container">
    <div class="row">
        <div class="col-lg-8" style="line-height:2">
            <div class="card rounded-0 border-0 p-3 f-16">
                {{ about_text|safe }}
            </div>
        </div>
        <div class="col-lg-4">
            {% include 'base_right.html' %}
        </div>
    </div>
</div>


{% endblock %}

iseek_backend/blog/templates/article_list.html
{% load humanize %}

<div class="summary-list">
{% for article in articles %}
    <div class="media mb-1 mb-sm-2 p-2 p-lg-3">
        <!-- 文章概览 -->
        <div class="media-body">
            <div class="text-muted mb-2 f-12">
{#                {% get_user_avatar_tag article.author %}#}
                <span>{{ article.author }}</span>
                <span><i class="fa fa-calendar-times-o ml-2 mr-1"></i>{{ article.create_time|naturalday}}</span>
            </div>
            <h2 class="mt-0 font-weight-bold text-info f-17">
                <a href="{{ article.get_absolute_url }}" target="_blank">{{ article.title}}</a>
            </h2>
            <p class="d-none d-sm-block mb-2 f-15">{{ article.summary|truncatechars:130 }}</p>
            <p class="d-block d-sm-none mb-2 f-15">{{ article.summary|truncatechars:64 }}</p>

            <!-- 文章分类 -->
            <div class="text-muted mb-0 f-12">
                <a class="cate" href="{{ article.topic.get_absolute_url }}" title="查看当前分类下更多文章">
                    <i class="fa fa-book mr-1"></i>{{ article.topic }}</a>
            </div>

        </div>

    </div>
{% endfor %}

</div>

iseek_backend/blog/templates/base.html
{## 这个地方引入 static 的文件路径 #}
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">

    <!-- 宽度等于当前设备的宽度，不缩放 -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>iSeek {% block blog_title %}{% endblock %}</title>

    <link rel="shortcut icon" href="{% static 'img/favicon.ico'%}" type="image/x-icon"/>

    <!-- 引入bootstrap.min.css -->
{#    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">#}

    <!-- Bootstrap and font-awesome CSS -->
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
          integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- blog CSS -->
    <link href="{% static 'css/base.css' %}?v=20171223.05" rel="stylesheet">

    {% block top-file %}{% endblock %}
</head>

<body>

<!--导航开始-->
{% include 'navbar.html' %}
<!--导航结束-->

<!-- todo: 回到顶部按钮 -->

<!--主要内容-->
<main>{% block base_content %}{% endblock %}</main>

</body>
</html>

iseek_backend/blog/templates/base_right.html
{% load blog_tags static %}

<!-- 个人空间 -->

<!-- 分类 -->
<div class="card border-0 rounded-0 px-3 mb-2 mb-md-3" id="category-card">
    <div class="card-header bg-white px-0">
        <strong><i class="fa fa-book mr-2 f-17"></i>文章分类</strong>
    </div>
    {% get_topic_list as topics %}
    <ul class="list-group list-group-flush f-16">
        {% for each in topics %}
        <li class="list-group-item d-flex justify-content-between align-items-center pr-2 py-2">
            <a class="category-item" href="{{ each.get_absolute_url }}"
               title="查看【{{ each.name }}】分类下所有文章">{{ each.name }}</a>
            <span class="badge text-center" title="当前分类下有{{ each.total_num }}篇文章">{{ each.total_num }}</span>
        </li>
        {% endfor %}
    </ul>
</div>

<!-- 标签 -->
<div class="card border-0 rounded-0 px-3 mb-2 mb-md-3" id="tag-card">
    <div class="card-header bg-white px-0">
        <strong><i class="fa fa-tags mr-2 f-17"></i>标&nbsp;签</strong>
    </div>
    <div class="card-body px-0 py-3">
        <div class="tag-cloud">
            {% get_tag_list as tag_list %}
            {% for tag in tag_list %}
            <a href="{{ tag.get_absolute_url }}" class="tags f-16" id="tag-{{ forloop.counter }}">
                {{ tag.name }}
            </a>
            {% endfor %}
        </div>
    </div>
</div>

iseek_backend/blog/templates/detail.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% load blog_tags %}

{% block head_title %}{{ article.title }}{% endblock %}

{% block top-file %}
<link href="{% static 'css/detail.css' %}?v=20180102.08" rel="stylesheet">
<link href="{% static 'css/github-colorful.css' %}?v=20180102.130" rel="stylesheet">
{% endblock %}

{% block base_content %}
<div class="container">
    <div class="row">
        <div class="col-lg-9">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb bg-white border-0 rounded-0 mb-2 py-2 f-15">
                    <li class="breadcrumb-item">
                        <i class="fa fa-home mr-1"></i><a href="{% url 'blog:index' %}">首页</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="{{ article.topic.get_absolute_url }}">{{ article.topic }}</a>
                    </li>
                    <li class="breadcrumb-item active d-none d-md-block" aria-current="page">{{ article.title }}</li>
                    <li class="breadcrumb-item active d-md-none" aria-current="page">当前位置</li>
                </ol>
            </nav>
            <div class="card rounded-0 border-0" id="article">
                <div class="card-body px-2 px-md-3 pb-0">
                    <h1 class="card-title text-center font-weight-bold text-info">{{ article.title }}</h1>
                    <hr>
                    <div class="text-center f-13">
                        <span class="mx-2" data-toggle="tooltip" data-placement="bottom"
                              title="最后编辑于{{ article.update_time|date:'Y年m月d日' }}">
                            {{ article.create_time }}
                        </span>
                    </div>
                    <div class="article-body mt-4 f-17" style="line-height:1.8">
                        {{ article.text|safe }}
                        <p class="font-weight-bold text-info">
                            <i class="fa fa-bullhorn mx-1"></i>
                            原创文章，转载请注明出处：{{ request.build_absolute_uri }}
                        </p>
                    </div>
                    <div class="tag-cloud my-4">
                        {% for tag in article.tags.all %}
                        <a class="tags f-16" href="{{ tag.get_absolute_url }}">{{ tag.name }}</a>
                        {% endfor %}
                    </div>
                    <nav class="more-page f-16">
                        <ul class="pagination justify-content-between">
                            <li class="page-item">
                                {% if article.get_pre %}
                                <a class="d-none d-md-block" href="{{ article.get_pre.get_absolute_url }}"
                                   title="上一篇：{{ article.get_pre.title }}">
                                    <i class="fa fa-chevron-left mr-1"></i>
                                    {{ article.get_pre.title|truncatechars:18 }}
                                </a>
                                <a class="d-md-none" href="{{ article.get_pre.get_absolute_url }}">
                                    <i class="fa fa-chevron-left mr-1"></i>上一篇</a>
                                {% endif %}
                            </li>
                            <li class="page-item">
                                {% if article.get_next %}
                                <a class="d-none d-md-block" href="{{ article.get_next.get_absolute_url }}"
                                   title="下一篇：{{ article.get_next.title }}">
                                    {{ article.get_next.title|truncatechars:18 }}
                                    <i class="fa fa-chevron-right ml-1"></i>
                                </a>
                                <a class="d-md-none" href="{{ article.get_next.get_absolute_url }}">
                                    下一篇<i class="fa fa-chevron-right ml-1"></i>
                                </a>
                                {% endif %}
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
        <!-- 文章目录 -->
        <div class="col-lg-3">
            <div class="article-toc d-none d-lg-block f-16">
                {{ article.toc|safe }}
            </div>
        </div>
    </div>
</div>
{% endblock %}

iseek_backend/blog/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}

{% block blog_title %}个人博客{% endblock %}

{% block base_content %}

<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <!-- 排序选项 -->
            <div class="text-secondary font-weight-bold py-2 f-15 choice">
                {% url 'blog:index' as index_url %}
                <a class="pb-2 {% if request.path == index_url %}active{% endif %}" href="{{ index_url }}">
                    <i class="fa fa-bars mr-1"></i>时间排序
                </a>
            </div>

            <!-- 文章列表 -->
            {% get_article_list articles %}
            {% if is_paginated %} {% load_pages %} {% endif %}
        </div>

        <!-- 主页右边栏 -->
        <div class="col-lg-4">
            {% include 'base_right.html' %}
        </div>

    </div>
</div>


{% endblock %}

iseek_backend/blog/templates/navbar.html
{## 这个地方引入 static 的文件路径 #}
{% load static %}

{## {% static "image/logo.png" %} 表示路径#}

{# 导航栏，样式，位置 #}
<nav class="navbar navbar-expand-md bg-white fixed-top blog-navbar py-md-0">
    {# 同时创建图像链接 #}
    <a class="navbar-brand d-md-none d-lg-block" href="{% url 'blog:index' %}">
        <img src="{% static "img/logo.png" %}" width="108" height="40" alt="iseek"/>
    </a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item mr-2">
                {% url 'blog:index' as index_url %}
                <a class="nav-link py-md-3 {% if request.path == index_url %}active{% endif %}"
                    href="{{ index_url }}"><i class="fa fa-home mr-1"></i>首页
                </a>
            </li>

            <li class="nav-item mr-2">
                {% url 'blog:about' as about_url %}
                <a class="nav-link py-md-3 {% if request.path == about_url %}active{% endif %}"
                    href="{{ about_url }}"><i class="fa fa-anchor mr-1"></i>关于
                </a>
            </li>

            <li class="nav-item mr-2">
                <a class="nav-link py-md-3" href="/admin/">后台</a>
            </li>
        </ul>
    </div>
</nav>

iseek_backend/blog/templates/pagination.html
<div class="text-center mt-2 mt-sm-1 mt-md-0 mb-3 f-16">
    {% if page_obj.has_previous %}
    <a class="text-success" href="?page={{ page_obj.previous_page_number }}">上一页</a>
    {% else %}
    <span class="text-secondary" title="当前页已经是首页">上一页</span>
    {% endif %}
    <span class="mx-2">第&nbsp;{{ page_obj.number }}&nbsp;/&nbsp;{{ paginator.num_pages }}&nbsp;页</span>
    {% if page_obj.has_next %}
    <a class="text-success" href="?page={{ page_obj.next_page_number }}">下一页</a>
    {% else %}
    <span class="text-secondary" title="当前页已经是末页">下一页</span>
    {% endif %}
</div>

iseek_backend/blog/templates/tag.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}
{% load blog_tags %}

{% block blog_title %}标签{% endblock %}

{% block base_content %}
<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <div class="description bg-white px-3 pt-3 pb-1">
                <p class="float-right mb-0">共<span class="mx-2 text-info">{{ articles.count }}</span>篇</p>
                <h1 class="f-17"><strong>文章标签：{{ tag.name }}</strong></h1>
                <p class="f-16">{{ tag.desc }}</p>
            </div>

            <div class="text-secondary font-weight-bold py-2 f-15 choice">
                {% url 'blog:tag' as tag_url %}
                <a class="pb-2 {% if request.path == tag_url %}active{% endif %}" href="{{ tag_url }}">
                    <i class="fa fa-bars mr-1"></i>时间排序</a>
            </div>
            {% get_article_list articles %}
        </div>

        <div class="col-lg-4">
            {% include 'base_right.html' %}
        </div>
    </div>
</div>
{% endblock %}

iseek_backend/blog/templates/topic.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% load blog_tags %}

{% block blog_title %}分类{% endblock %}

{% block base_content %}
<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <div class="description bg-white px-3 pt-3 pb-1">
                <p class="float-right mb-0">共<span class="mx-2 text-info">{{ articles.count }}</span>篇</p>
                <h1 class="f-17"><strong>文章分类：{{ topic.name }}</strong></h1>
                <p class="f-16">{{ topic.desc }}</p>
            </div>

            <div class="text-secondary font-weight-bold py-2 f-15 choice">
                {% url 'blog:topic' as topic_url %}
                <a class="pb-2 {% if request.path == topic_url %}active{% endif %}" href="{{ topic_url }}">
                    <i class="fa fa-bars mr-1"></i>时间排序</a>
            </div>
            {% get_article_list articles %}
        </div>

        <div class="col-lg-4">
            {% include 'base_right.html' %}
        </div>
    </div>
</div>
{% endblock %}